title: Home
# Include external resources
resources:
  - url: /local/my-custom-card.js
    type: js
  - url: /local/my-webfont.css
    type: css
  - url: /local/simple-thermostat.js?v=1
    type: module

# Optional background for all views. Check https://developer.mozilla.org/en-US/docs/Web/CSS/background for more examples.
#background: center / cover no-repeat url("/background.png") fixed

views:
    # View tab title.
  - title: South Carolina
    # Unique path for direct access /lovelace/${path}
    path: southcarolina
    # Optional background (overwrites the global background).
    #background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    #theme: slate
    # The cards to show on this view.
    cards:
      - type: vertical-stack
        cards:
        - type: picture-entity
          entity: camera.driveway_cam
          show_name: false
          show_state: false
        - type: picture-entity
          entity: camera.backyard_cam
          show_name: false
          show_state: false
      - type: media-control
        entity: media_player.samsung_tv_remote
      - type: vertical-stack
        cards:
        - type: custom:simple-thermostat
          entity: climate.trane_model_tzemt524aa21ma_cooling_1
          step_size: 1
          hide:
            temperature: true
          icon:
            heat: mdi:fire
            cool: mdi:snowflake
            eco: mdi:leaf
            off: mdi:power
            auto: mdi:autorenew
            idle: mdi:power
            away: mdi:leaf
          sensors:
            - entity: sensor.living_room_temperature
              name: Temperature
            - entity: sensor.living_room_humidity
              name: Humidity
        #- type: thermostat
        #  entity: climate.trane_model_tzemt524aa21ma_cooling_1
        - type: custom:simple-thermostat
          entity: climate.trane_model_tzemt524aa21ma_cooling_1_2
          step_size: 1
          hide:
            temperature: true
          icon:
            heat: mdi:fire
            cool: mdi:snowflake
            eco: mdi:leaf
            off: mdi:power
            auto: mdi:autorenew
            idle: mdi:power
            away: mdi:leaf
          sensors:
            - entity: sensor.loft_temperature
              name: Temperature
            - entity: sensor.loft_humidity
              name: Humidity
        #- type: thermostat
        #  entity: climate.trane_model_tzemt524aa21ma_cooling_1_2
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - light.zooz_zen24_bedroom
          - light.zooz_zen24_kitchen
          - light.zooz_zen24_livingroom
          - light.zooz_zen24_loft
          - light.living_room_fan_light
          - light.bedroom_fan_light
          - switch.aeotec_dsc26103_micro_switch_2nd_edition_switch
          - switch.aeotec_dsc26103_micro_switch_2nd_edition_switch_2
      - type: entities
        title: Computers
        show_header_toggle: false
        entities:
          - switch.grace_s_computer_wol
          - switch.nouzar_s_computer_wol
      - type: entities
        title: Fans
        show_header_toggle: false
        entities:
          - fan.bedroom_fan
          - switch.reverse_bedroom_fan
          - fan.living_room_fan
          - switch.reverse_living_room_fan
          - fan.office_fan
          - switch.reverse_office_fan
      

    # Specify a tab icon if you want the view tab to be an icon.
  - title: Boston
    # Title of the view. Will be used as the tooltip for tab icon
    #title: Second view
    cards:
        # Entities card will take a list of entities and show their state.
      - type: entities
        title: Computers
        show_header_toggle: false
        entities:
          - switch.caitlins_computer_wol_proxy
          - switch.seans_computer_wol_proxy
      - type: vertical-stack
        cards:
          - type: light
            entity: light.bedside
          - type: light
            entity: light.boston